# Generated by Django 5.2 on 2025-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_is_temporary_alter_route_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
    ]
