# Generated by Django 5.2 on 2025-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_backgroundimage_is_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
